stages:
  ingest:
    # REMOVED: PMC ingestion steps
    cmd: >
      python -m pipelines.ingestion.arxiv_metadata_ingest &&
      python -m pipelines.ingestion.arxiv_pdf_acquire
    deps:
      - pipelines/ingestion/arxiv_metadata_ingest.py
      - pipelines/ingestion/arxiv_pdf_acquire.py
    params:
      - ingestion
    outs:
      - data/raw

  process:
    cmd: python -m pipelines.processing.extracting_and_chunking_pdfs --input_dir data/raw/pdfs --output_dir data/processed/chunks
    deps:
      - pipelines/processing/extracting_and_chunking_pdfs.py
      - data/raw
    params:
      - processing
    outs:
      - data/processed/chunks

  embed:
    cmd: python -m pipelines.processing.build_embeddings_and_faiss --input_dir data/processed/chunks --output_dir data/processed/faiss
    deps:
      - pipelines/processing/build_embeddings_and_faiss.py
      - data/processed/chunks
    params:
      - indexing
    outs:
      - data/processed/faiss

  evaluate:
    cmd: python -m evaluation.evaluate
    deps:
      - evaluation/evaluate.py
      - data/processed/faiss
      - pipelines/evaluation/data/eval_queries.json
    params:
      - evaluation
    metrics:
      - evaluation/metrics.json:
          cache: false
    outs:
      - evaluation/results/