import json
import sys
import hashlib
from datetime import datetime, timezone
from pathlib import Path

# Add project root to path
sys.path.append(str(Path(__file__).parents[1]))

from utils.helper_functions import get_git_revision_hash

DATASET_MANIFEST = Path("data/versions/dataset_manifest.json")
# UPDATED: Match dvc.yaml output directory
INDEX_DIR = Path("data/processed/faiss") 
INDEX_MANIFEST = INDEX_DIR / "index_manifest.json"

# UPDATED: Match filenames generated by build_embeddings_and_faiss.py
FAISS_INDEX_FILE = "index.faiss" 
FAISS_META_FILE = "index_meta.json"

# Frozen Config for Retrieval
RETRIEVAL_CONFIG = {
    "embedding_model": "sentence-transformers/all-mpnet-base-v2",
    "embedding_dim": 768,
    "similarity_metric": "inner_product",
    "normalization": True
}

def hash_object(obj):
    """Deterministically hash a dictionary."""
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode("utf-8")).hexdigest()

def write_index_manifest():
    if not DATASET_MANIFEST.exists():
        print(f"CRITICAL: Dataset manifest not found at {DATASET_MANIFEST}")
        return

    with DATASET_MANIFEST.open("r", encoding="utf-8") as f:
        dataset_manifest = json.load(f)

    # 1. Create the Manifest Payload
    manifest = {
        "artifact_type": "faiss_index",
        "dataset_lineage": {
            "dataset_hash": dataset_manifest["dataset_hash"],
            "dataset_created_at": dataset_manifest["created_at"]
        },
        "config": RETRIEVAL_CONFIG,
        "files": {
            "index": FAISS_INDEX_FILE,
            "metadata": FAISS_META_FILE
        },
        "git_commit": get_git_revision_hash(),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }

    # 2. Compute Self-Hash (The ID of this specific index build)
    manifest["artifact_hash"] = hash_object(manifest)

    INDEX_DIR.mkdir(parents=True, exist_ok=True)

    with INDEX_MANIFEST.open("w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print(f"✅ Index Manifest Written to {INDEX_MANIFEST}")
    print(f"   Artifact Hash: {manifest['artifact_hash']}")

if __name__ == "__main__":
    write_index_manifest()